import { Component, OnInit, ViewChild, ElementRef, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AdminService } from '../core/services/admin.service';
import { AuthService } from '../core/services/auth.service';
import { Report } from '../core/models/report.models';
import Chart from 'chart.js/auto';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="page-container">
      <!-- Page Header -->
      <div class="page-header">
        <div class="page-title">
          <h2>Reports</h2>
          <p>Generate and export platform analytics</p>
        </div>
        <button class="btn btn-success" (click)="exportCsv()" [disabled]="reports.length === 0">
          ⬇ Export CSV
        </button>
      </div>

      <!-- KPI Cards -->
      <div class="kpi-grid">
        <div class="kpi-card">
          <div class="kpi-value">{{ reports.length }}</div>
          <div class="kpi-label">Total Reports</div>
        </div>
        <div class="kpi-card">
          <div class="kpi-value">{{ getCount('Claims') }}</div>
          <div class="kpi-label">Claims Reports</div>
        </div>
        <div class="kpi-card">
          <div class="kpi-value">{{ getCount('Policies') }}</div>
          <div class="kpi-label">Policy Reports</div>
        </div>
        <div class="kpi-card">
          <div class="kpi-value">{{ getCount('Users') }}</div>
          <div class="kpi-label">User Reports</div>
        </div>
      </div>

      <!-- Generate Report Form -->
      <div class="chart-wrapper" style="margin-bottom:1.5rem;">
        <div class="chart-title">Generate New Report</div>
        <form [formGroup]="reportForm" (ngSubmit)="generate()" class="inline-form">
          <div style="flex:1; min-width:200px;">
            <input formControlName="title" placeholder="Report title..." class="form-control" />
          </div>
          <div style="min-width:160px;">
            <select formControlName="reportType" class="form-control">
              <option value="Claims">Claims Report</option>
              <option value="Policies">Policies Report</option>
              <option value="Users">Users Report</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary" [disabled]="reportForm.invalid">
            📊 Generate
          </button>
        </form>
      </div>

      <!-- Charts Row -->
      <div class="charts-row" *ngIf="reports.length > 0">
        <div class="chart-wrapper">
          <div class="chart-title">Distribution by Type</div>
          <div class="chart-canvas-wrap">
            <canvas #doughnutCanvas></canvas>
          </div>
        </div>
        <div class="chart-wrapper">
          <div class="chart-title">Reports by Type</div>
          <div class="chart-canvas-wrap">
            <canvas #barCanvas></canvas>
          </div>
        </div>
      </div>

      <!-- Reports Table -->
      <table class="table" *ngIf="reports.length > 0">
        <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Type</th>
            <th>Generated By</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let r of reports; let i = index">
            <td style="color:#94a3b8; font-size:0.8rem;">{{ i + 1 }}</td>
            <td><strong>{{ r.title }}</strong></td>
            <td><span class="badge badge-info">{{ r.reportType }}</span></td>
            <td>Admin #{{ r.generatedBy }}</td>
            <td style="color:#64748b; font-size:0.8rem;">{{ r.generatedAt | date:'MMM d, y · h:mm a' }}</td>
          </tr>
        </tbody>
      </table>

      <div *ngIf="reports.length === 0" class="empty-state">
        <div class="empty-icon">📊</div>
        <h3>No reports yet</h3>
        <p>Generate your first report using the form above.</p>
      </div>
    </div>
  `,
  styles: [`
    .charts-row {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1.5rem;
      margin-bottom: 1.5rem;
    }
    .chart-canvas-wrap {
      position: relative;
      height: 260px;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .chart-canvas-wrap canvas {
      max-height: 260px;
    }
    @media (max-width: 768px) {
      .charts-row { grid-template-columns: 1fr; }
    }
  `]
})
export class ReportsComponent implements OnInit {
  reports: Report[] = [];
  reportForm: FormGroup;
  chartInstance: any = null;
  barChartInstance: any = null;

  @ViewChild('doughnutCanvas') doughnutCanvas!: ElementRef<HTMLCanvasElement>;
  @ViewChild('barCanvas') barCanvas!: ElementRef<HTMLCanvasElement>;

  getCount(type: string): number {
    return this.reports.filter(r => r.reportType === type).length;
  }

  constructor(
    private adminService: AdminService,
    private authService: AuthService,
    private fb: FormBuilder
  ) {
    this.reportForm = this.fb.group({
      title: ['', Validators.required],
      reportType: ['Claims', Validators.required]
    });
  }

  ngOnInit(): void {
    this.adminService.getReports().subscribe(r => {
      this.reports = r;
      setTimeout(() => this.renderChart(), 100);
    });
  }

  renderChart(): void {
    const types = ['Claims', 'Policies', 'Users'];
    const counts = types.map(t => this.getCount(t));
    const colors = ['#3b82f6', '#10b981', '#f59e0b'];
    const borderColors = ['#1e40af', '#059669', '#d97706'];

    // Doughnut chart
    if (this.doughnutCanvas?.nativeElement) {
      if (this.chartInstance) {
        this.chartInstance.destroy();
      }
      this.chartInstance = new Chart(this.doughnutCanvas.nativeElement, {
        type: 'doughnut',
        data: {
          labels: types,
          datasets: [{
            data: counts,
            backgroundColor: colors,
            borderColor: borderColors,
            borderWidth: 2,
            hoverOffset: 8
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: {
              position: 'bottom',
              labels: { padding: 16, font: { size: 12, family: 'Inter' } }
            }
          },
          cutout: '65%'
        }
      });
    }

    // Bar chart
    if (this.barCanvas?.nativeElement) {
      if (this.barChartInstance) {
        this.barChartInstance.destroy();
      }
      this.barChartInstance = new Chart(this.barCanvas.nativeElement, {
        type: 'bar',
        data: {
          labels: types,
          datasets: [{
            label: 'Reports',
            data: counts,
            backgroundColor: colors,
            borderColor: borderColors,
            borderWidth: 2,
            borderRadius: 8,
            borderSkipped: false
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { display: false }
          },
          scales: {
            y: {
              beginAtZero: true,
              ticks: { stepSize: 1, font: { family: 'Inter' } },
              grid: { color: '#f1f5f9' }
            },
            x: {
              ticks: { font: { family: 'Inter' } },
              grid: { display: false }
            }
          }
        }
      });
    }
  }

  generate(): void {
    const userId = this.authService.getUserId()!;
    this.adminService.generateReport({ ...this.reportForm.value, generatedBy: userId }).subscribe(r => {
      this.reports.unshift(r);
      this.reportForm.reset({ reportType: 'Claims' });
      setTimeout(() => this.renderChart(), 100);
    });
  }

  exportCsv(): void {
    const headers = ['ID', 'Title', 'Type', 'Generated By', 'Date'];
    const rows = this.reports.map(r =>
      [r.id, `"${r.title}"`, r.reportType, `Admin #${r.generatedBy}`, new Date(r.generatedAt).toLocaleString()]
    );
    const csv = [headers, ...rows].map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SmartSure_Reports_${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }
}
