import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AdminService } from '../core/services/admin.service';
import { AuthService } from '../core/services/auth.service';
import { Report } from '../core/models/report.models';
import Chart from 'chart.js/auto';
import { reportTitleValidator, getErrorMessage } from '../shared/validators/app.validators';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './reports.component.html',
  styleUrls: ['./reports.component.css']
})
export class ReportsComponent implements OnInit {
  reports: Report[] = [];
  reportForm: FormGroup;
  chartInstance: any = null;
  barChartInstance: any = null;
  loading = false;
  generating = false;
  errorMsg = '';
  successMsg = '';

  @ViewChild('doughnutCanvas') doughnutCanvas!: ElementRef<HTMLCanvasElement>;
  @ViewChild('barCanvas') barCanvas!: ElementRef<HTMLCanvasElement>;

  getCount(type: string): number { return this.reports.filter(r => r.reportType === type).length; }

  typeBadge(type: string): string {
    const map: Record<string, string> = { Claims: 'rp-badge-claims', Policies: 'rp-badge-policies', Users: 'rp-badge-users' };
    return map[type] ?? 'rp-badge-claims';
  }

  typeIcon(type: string): string {
    const map: Record<string, string> = { Claims: 'fa-solid fa-file-circle-check', Policies: 'fa-solid fa-shield-halved', Users: 'fa-solid fa-users' };
    return map[type] ?? 'fa-solid fa-file';
  }

  constructor(
    private adminService: AdminService,
    private authService: AuthService,
    private fb: FormBuilder
  ) {
    this.reportForm = this.fb.group({
      title:      ['', [Validators.required, reportTitleValidator]],
      reportType: ['Claims', Validators.required]
    });
  }

  isInvalid(f: string): boolean { const c = this.reportForm.get(f); return !!(c?.invalid && (c.touched || c.dirty)); }
  isValid(f: string):   boolean { const c = this.reportForm.get(f); return !!(c?.valid  && (c.touched || c.dirty)); }
  err(f: string):       string  { return getErrorMessage(f, this.reportForm.get(f)?.errors ?? null); }

  ngOnInit(): void {
    this.loading = true; this.errorMsg = '';
    this.adminService.getReports().subscribe({
      next: r => { this.reports = r; this.loading = false; setTimeout(() => this.renderChart(), 100); },
      error: () => { this.loading = false; this.errorMsg = 'Failed to load reports. Make sure AdminService is running.'; }
    });
  }

  renderChart(): void {
    const types = ['Claims', 'Policies', 'Users'];
    const counts = types.map(t => this.getCount(t));
    const colors = ['#3b82f6', '#10b981', '#f59e0b'];
    const borders = ['#1e40af', '#059669', '#d97706'];
    if (this.doughnutCanvas?.nativeElement) {
      this.chartInstance?.destroy();
      this.chartInstance = new Chart(this.doughnutCanvas.nativeElement, {
        type: 'doughnut',
        data: { labels: types, datasets: [{ data: counts, backgroundColor: colors, borderColor: borders, borderWidth: 2, hoverOffset: 8 }] },
        options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { padding: 16, font: { size: 12 } } } }, cutout: '65%' }
      });
    }
    if (this.barCanvas?.nativeElement) {
      this.barChartInstance?.destroy();
      this.barChartInstance = new Chart(this.barCanvas.nativeElement, {
        type: 'bar',
        data: { labels: types, datasets: [{ label: 'Reports', data: counts, backgroundColor: colors, borderColor: borders, borderWidth: 2, borderRadius: 8, borderSkipped: false as any }] },
        options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { y: { beginAtZero: true, ticks: { stepSize: 1 }, grid: { color: '#f1f5f9' } }, x: { grid: { display: false } } } }
      });
    }
  }

  generate(): void {
    if (this.reportForm.invalid) return;
    this.generating = true; this.errorMsg = ''; this.successMsg = '';
    this.adminService.generateReport({ ...this.reportForm.value, generatedBy: this.authService.getUserId()! }).subscribe({
      next: r => {
        this.reports.unshift(r); this.reportForm.patchValue({ title: '' });
        this.generating = false; this.successMsg = `Report "${r.title}" generated successfully.`;
        setTimeout(() => { this.successMsg = ''; }, 4000);
        setTimeout(() => this.renderChart(), 100);
      },
      error: err => { this.generating = false; this.errorMsg = err.error?.message || 'Failed to generate report.'; }
    });
  }

  exportCsv(): void {
    if (!this.reports.length) return;
    const headers = ['ID', 'Title', 'Type', 'Generated By', 'Date'];
    const rows = this.reports.map(r => [r.id, `"${r.title}"`, r.reportType, `Admin #${r.generatedBy}`, new Date(r.generatedAt).toLocaleString()]);
    const csv = [headers, ...rows].map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SmartSure_Reports_${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }
}
